### ISSUE TITLE
Create an AWS S3 bucket for assets

### ISSUE THREAD

**Issue by pmgledhill102** [aws-lug/aws-lug-meetups#12]
We need somewhere to store public ally assessible assets.

**Comment by pmgledhill102** [comment]
Created...
<https://aws-lug-assets.s3.eu-west-2.amazonaws.com/>

Example file...
<https://aws-lug-assets.s3.eu-west-2.amazonaws.com/graphql.png>

**Comment by pmgledhill102** [comment]
Need to create access for other organisers to upload to bucket

**Comment by clearcoding** [comment]
Not going to do this . Chose Meetup reop
