### ISSUE TITLE
Talk submission: Lessons learned building an e-commerce platform in 6 months at cinch

### ISSUE THREAD

**Issue by cinch-toli** [aws-lug/aws-lug-meetups#19]
**Abstract**

_Event-driven architectures is a powerful way to decouple development teams, allowing them to build autonomously and release new features fast. But what does this look like in practice? In this session, you will hear from AWS and cinch, one of the fastest growing start-ups in the UK. You will learn how cinch built an entirely new event-driven e-commerce platform in just 6 months. We will explore cinch’s architecture and AWS services used, the best practices that helped cinch succeed, and the considerations for anyone looking to increase team agility and feature release velocity._

**Speakers**

Myself and [Emily Shea](https://twitter.com/em__shea) from AWS

**Comment by cinch-toli** [comment]
We are both available on September 13th, if there is a spot.

**Comment by pmgledhill102** [comment]
@cinch-toli - I've updated the MeetUp with your great abstract. The rest of the event details need a bit of polish, and then I'll get a reminder out to the community. Really looking forward to the talk.

**Comment by cinch-toli** [comment]
Thank you! Is September 13th locked as a date?

**Comment by pmgledhill102** [comment]
Yes it is.

And good luck tomorrow (I think it's EDA day?)

**Comment by maddop** [comment]
Successful presentation and session.  Thanks.
