### ISSUE TITLE
Organise 3rd November event

### ISSUE THREAD

**Issue by clearcoding** [aws-lug/aws-lug-meetups#21]
Lets agree on content and venue :)

**Comment by clearcoding** [comment]
Decsions:
DOES would be a good venue and would support a workshop type sessions
Decision to be finalised on which workshop to use either
 https://github.com/infinityworks/101-Sessions/tree/master/sessions/AwsCDKTypescript-100/101
or 
https://cdkworkshop.com/20-typescript/30-hello-cdk/200-lambda.html

**Comment by clearcoding** [comment]
Looking to put together the invite by next leader meeting on 17th October

**Comment by pmgledhill102** [comment]
VERY successful meet-up held. Workshop format brought some new people, and given the feedback we received everybody enjoyed it. Definitely want to look at running some more workshop sessions in 2023.
