### ISSUE TITLE
Call for speakers form

### ISSUE THREAD

**Issue by pmgledhill102** [aws-lug/aws-lug-meetups#39]
Create a call for speaker form:
* Gather required info
* Set expectations
* Provide support for new speakers - including suggestions on tooling

Maybe use some of the excellent content from the London MeetUp: https://www.meetup.com/awsuguk/

**Comment by katieraby** [comment]
Have drafted out a speaker form for review, and saved in the Google drive :)

**Comment by katieraby** [comment]
https://forms.gle/gvimByKRVfqGPgSx7
